ci: refactor ci scripts

diff --git a/.github/workflows/stage.yml b/.github/workflows/stage.yml
--- a/.github/workflows/stage.yml
+++ b/.github/workflows/stage.yml
@@ -12,7 +12,7 @@ on:
         description: "The Java version the workflow should use"
         required: false
         type: number
-        default: 21
+        default: 25
       retention_days:
         description: "Artifact retention days (default: 7)"
         required: false
@@ -52,7 +52,7 @@ jobs:
     runs-on: ${{ inputs.os }}
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v5
+        uses: actions/checkout@v7
         with:
           fetch-depth: 1 # Shallow clone for faster checkout
 
@@ -67,7 +67,7 @@ jobs:
       # Get version field in project properties file for snapshot version
       - name: Get Project Version
         id: version
-        uses: ./.github/actions/version
+        uses: ./.github/actions/getversion
         with:
           snapshot_suffix: ${{ inputs.snapshot_suffix }}
 
@@ -87,20 +87,40 @@ jobs:
       # Generate build provenance attestations if enabled
       - name: Generate Build Provenance Attestations
         if: ${{ inputs.generate_attestations }}
-        uses: actions/attest-build-provenance@v3
+        uses: actions/attest@v4
         with:
-          subject-path: "${{ github.workspace }}/build/libs/*"
+          subject-path: |
+            ${{ github.workspace }}/api/build/libs/*.jar
+            ${{ github.workspace }}/paper/build/libs/*.jar
 
       # Upload the snapshot artifacts
       - name: Upload Snapshot Artifacts
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v7
         with:
           name: Snapshot-${{ github.run_number }}
-          path: ${{ github.workspace }}/build/libs/
+          path: |
+            ${{ github.workspace }}/api/build/libs/
+            ${{ github.workspace }}/paper/build/libs/
           retention-days: ${{ inputs.retention_days }}
           if-no-files-found: error
 
-      # Publish to maven TODO
+      # Publish to maven
+#      - name: Upload & Publish to Maven Repository
+#        shell: bash
+#        run: |
+#          set +e  # Don't exit immediately on error
+#          ./gradlew publish -PaltVer=${{ steps.version.outputs.version }} -x test
+#          PUBLISHING_EXIT_CODE=$?
+#
+#          if [ PUBLISHING_EXIT_CODE -ne 0 ]; then
+#            echo "::error::Publishing maven artifacts failed with exit code PUBLISHING_EXIT_CODE"
+#            exit PUBLISHING_EXIT_CODE
+#          fi
+#        env:
+#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
+#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY_PASSWORD }}
 
   # Update version in properties file for release builds
   stage-version:
@@ -111,14 +131,14 @@ jobs:
       # Checkout repository
       - name: Checkout Repository
         if: ${{ !contains(github.ref_name, inputs.prerelease_suffix) }}
-        uses: actions/checkout@v5
+        uses: actions/checkout@v7
         with:
           fetch-depth: 1 # Shallow clone for faster checkout
 
       # Update version field in project properties file
       - name: Update Project Version
         if: ${{ !contains(github.ref_name, inputs.prerelease_suffix) }}
-        uses: ./.github/actions/updateversion
+        uses: ./.github/actions/setversion
         with:
           version: ${{ github.ref_name }}
 
@@ -137,7 +157,7 @@ jobs:
     runs-on: ${{ inputs.os }}
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v5
+        uses: actions/checkout@v7
         with:
           fetch-depth: 1 # Shallow clone for faster checkout
 
@@ -170,16 +190,36 @@ jobs:
 
       - name: Generate Build Provenance Attestations
         if: ${{ inputs.generate_attestations }}
-        uses: actions/attest-build-provenance@v3
+        uses: actions/attest@v4
         with:
-          subject-path: "${{ github.workspace }}/build/libs/*"
+          subject-path: |
+            ${{ github.workspace }}/api/build/libs/*.jar
+            ${{ github.workspace }}/paper/build/libs/*.jar
 
       - name: Upload Release Artifacts
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v7
         with:
           name: Release
-          path: ${{ github.workspace }}/build/libs/
+          path: |
+            ${{ github.workspace }}/api/build/libs/
+            ${{ github.workspace }}/paper/build/libs/
           retention-days: ${{ inputs.retention_days }}
           if-no-files-found: error
 
-      # Publish to maven TODO
+#      # Publish to maven
+#      - name: Upload & Publish to Maven Repository
+#        shell: bash
+#        run: |
+#          set +e  # Don't exit immediately on error
+#          ./gradlew publishAllPublicationsToMavenCentralRepository -PaltVer=${{ steps.version.outputs.version }} -x test
+#          PUBLISHING_EXIT_CODE=$?
+#
+#          if [ PUBLISHING_EXIT_CODE -ne 0 ]; then
+#            echo "::error::Publishing maven artifacts failed with exit code PUBLISHING_EXIT_CODE"
+#            exit PUBLISHING_EXIT_CODE
+#          fi
+#        env:
+#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
+#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY }}
+#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_GPG_SECRET_KEY_PASSWORD }}
